import { SETTING_TYPES, SettingsType } from "@deskthing/types";

export enum RECORDER_SETTING_IDS {
  AUDIO_FORMAT = 'audio_format',
  SAMPLE_RATE = 'sample_rate',
  CHANNELS = 'channels',
  BITS_PER_SAMPLE = 'bits_per_sample',
  CHUNK_DURATION = 'chunk_duration',
}

export type RecorderSettingsType = {
  [RECORDER_SETTING_IDS.AUDIO_FORMAT]: string;
  [RECORDER_SETTING_IDS.SAMPLE_RATE]: string;
  [RECORDER_SETTING_IDS.CHANNELS]: string;
  [RECORDER_SETTING_IDS.BITS_PER_SAMPLE]: string;
  [RECORDER_SETTING_IDS.CHUNK_DURATION]: number;
}

export type RawRecorderSettingsType = {
  [RECORDER_SETTING_IDS.AUDIO_FORMAT]: SettingsType & { type: SETTING_TYPES.SELECT; id: RECORDER_SETTING_IDS.AUDIO_FORMAT };
  [RECORDER_SETTING_IDS.SAMPLE_RATE]: SettingsType & { type: SETTING_TYPES.SELECT; id: RECORDER_SETTING_IDS.SAMPLE_RATE };
  [RECORDER_SETTING_IDS.CHANNELS]: SettingsType & { type: SETTING_TYPES.SELECT; id: RECORDER_SETTING_IDS.CHANNELS };
  [RECORDER_SETTING_IDS.BITS_PER_SAMPLE]: SettingsType & { type: SETTING_TYPES.SELECT; id: RECORDER_SETTING_IDS.BITS_PER_SAMPLE };
  [RECORDER_SETTING_IDS.CHUNK_DURATION]: SettingsType & { type: SETTING_TYPES.NUMBER; id: RECORDER_SETTING_IDS.CHUNK_DURATION };
}

