import { CONTROL_OPTIONS } from "@shared/types/discord";

export const XL_CONTROLS_ENABLED = true;
export const XL_CONTROL_PADDING_TOP = 4;
export const XL_CONTROL_PADDING_BOTTOM = 4;
export const XL_CONTROL_MARGIN_BOTTOM = 0;
export const XL_CONTROL_INNER_PADDING_Y = 4;
export const XL_CONTROL_BUTTON_SIZE = 96; // px
export const XL_CONTROL_MIN_HEIGHT = XL_CONTROL_BUTTON_SIZE;
export const XL_CONTROL_TOTAL_HEIGHT =
  XL_CONTROL_MIN_HEIGHT +
  XL_CONTROL_PADDING_TOP +
  XL_CONTROL_PADDING_BOTTOM +
  XL_CONTROL_MARGIN_BOTTOM +
  XL_CONTROL_INNER_PADDING_Y * 2;
export const XL_CONTROL_FALLBACK_ORDER: CONTROL_OPTIONS[] = [
  CONTROL_OPTIONS.MUTE,
  CONTROL_OPTIONS.DEAFEN,
  CONTROL_OPTIONS.DISCONNECT,
];
