export { Icon as IconX } from './svgs/IconX'
export { Icon as VolumeOff } from './svgs/IconVolumeOff'
export { Icon as IconVolume } from './svgs/IconVolume'
export { Icon as IconUserCircle } from './svgs/IconUserCircle'
export { Icon as IconSkip } from './svgs/IconSkip'
export { Icon as IconRewind } from './svgs/IconRewind'
export { Icon as IconPause } from './svgs/IconPause'
export { Icon as IconPlay } from './svgs/IconPlay'
export { Icon as IconCallDiscord } from './svgs/IconCallDiscord'
export { Icon as IconDeafenedDiscord } from './svgs/IconDeafenedDiscord'
export { Icon as IconDeafenedOffDiscord } from './svgs/IconDeafenedOffDiscord'
export { Icon as IconMicDiscord } from './svgs/IconMicDiscord';
export { Icon as IconMicOffDiscord } from './svgs/IconMicOffDiscord';
export { Icon as IconVolumeUp } from './svgs/IconVolumeUp';
export { Icon as IconVolumeDown } from './svgs/IconVolumeDown';